export const actionTypes = {
  ADD_NEW_USER: "ADD_NEW_USER",
  SET_TOKEN: "SET_TOKEN",
  SET_ERROR: "SET_ERROR",
  CURRENT_USER_INFO: "CURRENT_USER_INFO",
  SET_CATEGORY_LIST: "SET_CATEGORY_LIST",
  SET_CATEGORY_FOR_FILTER: "SET_CATEGORY_FOR_FILTER",
  SET_SINGLE_CATEGORY_FOR_EDIT: "SET_SINGLE_CATEGORY_FOR_EDIT",
};
